# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bigsmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeinterval', models.FloatField(blank=True, db_column='TimeInterval', null=True)),
                ('handicap', models.FloatField(blank=True, db_column='Handicap', null=True)),
                ('big', models.FloatField(blank=True, db_column='Big', null=True)),
                ('small', models.FloatField(blank=True, db_column='Small', null=True)),
                ('half_big', models.FloatField(blank=True, db_column='half_big', null=True)),
                ('half_small', models.FloatField(blank=True, db_column='half_small', null=True)),
                ('half_handicap', models.FloatField(blank=True, db_column='half_handicap', null=True)),
            ],
            options={
                'verbose_name': '大小表',
                'verbose_name_plural': '大小表',
            },
        ),
        migrations.CreateModel(
            name='Companyodds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=200)),
                ('updatetime', models.DateTimeField(blank=True, db_column='Updatetime', null=True)),
            ],
            options={
                'verbose_name': '赔率表',
                'verbose_name_plural': '赔率表',
            },
        ),
        migrations.CreateModel(
            name='Eventinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '联赛',
                'verbose_name_plural': '联赛',
            },
        ),
        migrations.CreateModel(
            name='Gameinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homename', models.CharField(blank=True, db_column='HomeName', max_length=100, null=True)),
                ('gametime', models.DateTimeField(db_column='GameTime')),
                ('visitname', models.CharField(blank=True, db_column='VisitName', max_length=100, null=True)),
                ('Companyodds', models.ManyToManyField(blank=True, to='web.Companyodds', verbose_name='比赛的开注公司')),
                ('eventid', models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.DO_NOTHING, to='web.Eventinfo')),
            ],
            options={
                'verbose_name': '比赛信息',
                'verbose_name_plural': '比赛信息',
            },
        ),
        migrations.CreateModel(
            name='Letball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.CharField(blank=True, max_length=10, null=True)),
                ('right', models.CharField(blank=True, max_length=10, null=True)),
                ('half_left', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('half_right', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('Handicap', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('Half_handicap', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('companyid', models.ForeignKey(blank=True, db_column='CompanyId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Companyodds')),
            ],
            options={
                'verbose_name': '让球赔率',
                'verbose_name_plural': '让球赔率',
            },
        ),
        migrations.CreateModel(
            name='Teaminfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '队伍信息',
                'verbose_name_plural': '队伍信息',
            },
        ),
        migrations.CreateModel(
            name='Winalone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homefullwinodds', models.FloatField(db_column='HomeFullWinOdds')),
                ('homefulldefeatodds', models.FloatField(db_column='HomeFullDefeatOdds')),
                ('fulldrawodds', models.FloatField(db_column='FullDrawOdds')),
                ('homehalfwinodds', models.FloatField(blank=True, db_column='HomeHalfWinOdds', null=True)),
                ('homehalfdefeatodds', models.FloatField(blank=True, db_column='HomeHalfDefeatOdds', null=True)),
                ('halfdrawodds', models.FloatField(blank=True, db_column='HalfDrawOdds', null=True)),
                ('companyid', models.ForeignKey(db_column='CompanyId', on_delete=django.db.models.deletion.CASCADE, to='web.Companyodds')),
            ],
            options={
                'verbose_name': '独赢赔率',
                'verbose_name_plural': '独赢赔率',
            },
        ),
        migrations.AddField(
            model_name='bigsmall',
            name='companyid',
            field=models.ForeignKey(db_column='CompanyId', on_delete=django.db.models.deletion.CASCADE, to='web.Companyodds'),
        ),
    ]
