# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200229_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsmall',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
        migrations.AlterField(
            model_name='letball',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
        migrations.AlterField(
            model_name='winalone',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
    ]
