# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-01 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200301_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsmall',
            name='half_handicap',
            field=models.CharField(blank=True, db_column='Half_handicap', default='0', max_length=11),
        ),
        migrations.AlterField(
            model_name='bigsmall',
            name='handicap',
            field=models.CharField(blank=True, db_column='Handicap', default='0', max_length=11),
        ),
    ]
