# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-02 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200301_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='eventid',
            field=models.ForeignKey(db_column='EventId', default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Eventinfo'),
        ),
    ]
