# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-02 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_teaminfo_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='eventid',
            field=models.ForeignKey(db_column='EventId', on_delete=django.db.models.deletion.CASCADE, to='web.Eventinfo'),
        ),
    ]
