# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200302_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigsmall',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
        migrations.AddField(
            model_name='letball',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
        migrations.AddField(
            model_name='winalone',
            name='gameinfo',
            field=models.ForeignKey(blank=True, db_column='GameinfoId', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Gameinfo'),
        ),
    ]
