# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200302_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='detaild',
            field=models.TextField(default=models.CharField(max_length=100, unique=True), max_length=255),
        ),
    ]
