# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-03 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200303_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='detaild',
        ),
    ]
