# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-03 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_teaminfo_detaild'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='detaild',
            field=models.TextField(default='<django.db.models.fields.CharField>', max_length=255),
        ),
    ]
