# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_teaminfo_detaild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='detaild',
            field=models.TextField(default='', max_length=255),
        ),
    ]
