# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200303_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='detaild',
            field=models.TextField(default='', max_length=255),
        ),
    ]
