# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_eventinfo_detaild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigsmall',
            name='half_big',
        ),
        migrations.RemoveField(
            model_name='bigsmall',
            name='half_handicap',
        ),
        migrations.RemoveField(
            model_name='bigsmall',
            name='half_small',
        ),
        migrations.RemoveField(
            model_name='letball',
            name='Half_handicap',
        ),
        migrations.RemoveField(
            model_name='letball',
            name='half_left',
        ),
        migrations.RemoveField(
            model_name='letball',
            name='half_right',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='fulldrawodds',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='halfdrawodds',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='homefulldefeatodds',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='homefullwinodds',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='homehalfdefeatodds',
        ),
        migrations.RemoveField(
            model_name='winalone',
            name='homehalfwinodds',
        ),
        migrations.AddField(
            model_name='bigsmall',
            name='is_half',
            field=models.BooleanField(db_column='is_half', default=0),
        ),
        migrations.AddField(
            model_name='letball',
            name='is_half',
            field=models.BooleanField(db_column='is_half', default=0),
        ),
        migrations.AddField(
            model_name='winalone',
            name='draw',
            field=models.FloatField(db_column='draw', default=0),
        ),
        migrations.AddField(
            model_name='winalone',
            name='is_half',
            field=models.BooleanField(db_column='is_half', default=0),
        ),
        migrations.AddField(
            model_name='winalone',
            name='lose',
            field=models.FloatField(db_column='lose', default=0),
        ),
        migrations.AddField(
            model_name='winalone',
            name='win',
            field=models.FloatField(db_column='win', default=0),
        ),
    ]
