# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-04 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200304_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinfo',
            old_name='detaild',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='teaminfo',
            old_name='detaild',
            new_name='detail',
        ),
    ]
