# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20200304_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letball',
            old_name='right',
            new_name='lbright',
        ),
        migrations.RemoveField(
            model_name='letball',
            name='left',
        ),
        migrations.AddField(
            model_name='bigsmall',
            name='playclass',
            field=models.BooleanField(db_column='playclass', default=0),
        ),
        migrations.AddField(
            model_name='letball',
            name='lbleft',
            field=models.FloatField(db_column='lbleft', default=0),
        ),
        migrations.AddField(
            model_name='letball',
            name='playclass',
            field=models.BooleanField(db_column='playclass', default=0),
        ),
        migrations.AddField(
            model_name='winalone',
            name='playclass',
            field=models.BooleanField(db_column='playclass', default=0),
        ),
    ]
