# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-04 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200304_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letball',
            name='lbright',
            field=models.FloatField(db_column='lbright', default=0),
        ),
    ]
