# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-05 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200304_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='awayname',
            field=models.CharField(blank=True, db_column='VisitName1', max_length=100, null=True),
        ),
    ]
