# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-05 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_gameinfo_awayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='visitname',
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='awayname',
            field=models.CharField(blank=True, db_column='AwayName', max_length=100, null=True),
        ),
    ]
