# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-06 01:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20200305_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigsmall',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 9, 1, 57, 751338)),
        ),
        migrations.AddField(
            model_name='letball',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 9, 1, 57, 754330)),
        ),
        migrations.AddField(
            model_name='winalone',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 9, 1, 57, 756325)),
        ),
    ]
