# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-06 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20200306_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigsmall',
            name='updatetime',
            field=models.DateTimeField(default='2020-03-05 20:28:22'),
        ),
        migrations.AlterField(
            model_name='companyodds',
            name='updatetime',
            field=models.DateTimeField(db_column='Updatetime', default='2020-03-05 20:28:22'),
        ),
        migrations.AlterField(
            model_name='letball',
            name='updatetime',
            field=models.DateTimeField(default='2020-03-05 20:28:22'),
        ),
        migrations.AlterField(
            model_name='winalone',
            name='updatetime',
            field=models.DateTimeField(default='2020-03-05 20:28:22'),
        ),
    ]
